version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  server:
    build: ./leaveboard-server
    container_name: leaveboard-server
    restart: unless-stopped
    env_file: ./.env
    depends_on: [mongo]
    ports: ["${PORT:-7088}:${PORT:-7088}"]
    # volumes:
    #   - ./leaveboard-server:/app
    #   - /app/node_modules
    # Uncomment the line below during development - hot reload
    # command: node --watch index.js

  client:
    build:
      context: ./leaveboard-client
      args:
        VITE_BASE_URL: ${VITE_BASE_URL:-http://localhost:7088}
    container_name: leaveboard-client
    restart: unless-stopped
    depends_on: [server]
    ports: ["7091:7091"]
    # volumes:
    #   - ./leaveboard-client:/app
    #   - /app/node_modules
    #   - /app/dist
    # Uncomment the line below during development - hot reload
    # command: npm run dev -- --host 0.0.0.0 --port 7091

volumes:
  mongo_data:
